import type { Metadata } from "next";
import "./globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "@/app/components/provider";
import { JotaiClientProvider } from "./components/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/convex.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexAuthNextjsServerProvider>
      <html lang="en">
        <body className="bg-[#202020] text-[#d0d0d0]">
          <JotaiClientProvider>
            <ConvexClientProvider>{children}</ConvexClientProvider>
          </JotaiClientProvider>
        </body>
      </html>
    </ConvexAuthNextjsServerProvider>
  );
}
